---

  - name: Install base package
    apt: name=python-passlib state=installed
    when: basic_auth_path is defined
    tags: basicAuth


  - name: generate htpasswd file
    htpasswd:
      path: "{{ basic_auth_path }}"
      name: "{{ basic_auth_name }}"
      password: "{{ basic_auth_password }}"
      owner: "www-data"
      group: "www-data"
      mode: "0640"
    when: basic_auth_path is defined
    tags: basicAuth
