- name: generate ssh for jenkins
  user: name=jenkins generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  register: ssh_key_jenkins
  tags: livinglab

- name: set jenkins public key
  set_fact: ssh_public_key_jenkins="{{ ssh_key_jenkins.ssh_public_key }}"
  tags: livinglab
